import { randomUUID } from 'node:crypto';

import { ValidationError } from '../errors/domain-error';

/**
 * Every aggregate in the PIM is identified by a UUID v4 (see standard in CLAUDE.md).
 *
 * Rationale: identifiers are generated by the application, not by the database, so a
 * use case can build a full aggregate — and enqueue jobs referencing it — before the
 * transaction commits. It also keeps IDs stable across the ERP/PIM boundary.
 */
export type Uuid = string & { readonly __brand: 'Uuid' };

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function newUuid(): Uuid {
  return randomUUID() as Uuid;
}

export function isUuid(value: string): value is Uuid {
  return UUID_PATTERN.test(value);
}

export function assertUuid(value: string, field = 'id'): Uuid {
  if (!isUuid(value)) {
    throw new ValidationError(`Invalid UUID for "${field}"`, { field });
  }
  return value as Uuid;
}
